### ISSUE TITLE
BWMirror API supports only x86 architecture.

### ISSUE THREAD

**Issue by shinmm** [SamsungSDS-Contest/2017Guide#9]
TutorialLevel0Bot 실행하면 다음과 같은 에러가 납니다.

%---------------------------------------------------------------------------------------------------------------
 Exception in thread "main" java.lang.ExceptionInInitializerError
	at MyBotModule.<init>(MyBotModule.java:13)
	at Main.main(Main.java:10)
Caused by: java.lang.UnsupportedOperationException: BWMirror API supports only x86 architecture.
	at bwapi.Mirror.<clinit>(Mirror.java:65)
	... 2 more
%----------------------------------------------------------------------------------------------------------------

실행 환경
 - Eclipse Version : Neon.3 x64
 - Window 7 x64

 ※ 64 비트 지원에 대한 안내가 따로 있었나요?

**Comment by TekseonShin** [comment]
JAVA 로 개발하시는 분께서는 JDK 32비트 버전을 사용해주시면 감사하겠습니다.
(README 및 wiki 에 적어놓았습니다)

JAVA 로 개발시 필수적으로 사용하게 되는 BWMirror 라이브러리가 
JDK 32비트 버전에서만 작동하기 때문입니다.

JDK 버전은 1.7 이상 버전이면 무엇이든 상관없습니다.

감사합니다~
